image_size: [128, 128]
batch_size: 32
epochs: 20
num_quality_classes: 3
num_region_classes: 7

train_dir: "data/train"
val_dir: "data/val"
model_save_path: "checkpoints/model_best.h5"

quality_classes: ["low_quality", "medium_quality", "high_quality"]
region_classes: ["region1", "region2", "region3", "region4", "region5", "region6", "region7"]
